# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eddie Hinkle
email: hello@eddiehinkle.com
description: > # this means to ignore newlines until "baseurl:"
  This is a simple website and blog by Eddie. I'm working on making it a lot nicer and a lot prettier soon. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eddiehinkle.com" # the base hostname & protocol for your site
twitter_username: eddiehinkle
github_username: edwardhinkle
instagram_username: eddiehinkle
facebook_username: EdwardTHinkle
first_name: Eddie
last_name: Hinkle
applenews_id: TlUsl76dFRNCfv54V0xuVJQ
permalink: /:year/:month/:day/:title.html

remoteUrl: https://eddiehinkle.com
localUrl: https://eddiehinkle.com

endpoints:
  authorization_endpoint: https://indieauth.com/auth
  token_endpoint: https://tokens.indieauth.com/token
  micropub: https://eddiehinkle.com/micropub
  webmention: https://webmention.io/eddiehinkle.com/webmention
  microsub: http://influx.abode/eddiehinkle.com/microsub
  pingback: https://webmention.io/eddiehinkle.com/xmlrpc

source: _source
destination: _build

# Build settings
markdown: kramdown

private_posts: false

collections:
  note:
    output: true
    permalink: /social/:year/:month/:title/
  podcasts:
    output: true
    permalink: /podcasts/:title/
  media:
    output: true
    permalink: /:path/:title/

jekyll-archives:
  enabled:
    - tags
  layout: 'archive'
  permalinks:
    tag: '/tag/:name/'
