remoteUrl: http://eddie2.test
localUrl: http://eddie2.test
url: http://eddie2.test

endpoints:
  authorization_endpoint: http://eddie2.test/auth/
  token_endpoint: https://tokens.indieauth.com/token
  micropub: https://eddie2.test/micropub
  webmention: https://webmention.io/eddie.dev/webmention
  microsub: http://influx.abode/eddie.dev/microsub
  pingback: https://webmention.io/eddie.dev/xmlrpc