private_posts: true
remoteUrl: http://eddie.dev
localUrl: http://eddie.dev
url: http://eddie.dev

endpoints:
  authorization_endpoint: https://indieauth.com/auth
  token_endpoint: https://tokens.indieauth.com/token
  micropub: https://eddie.dev/micropub
  webmention: https://webmention.io/eddie.dev/webmention
  microsub: http://influx.abode/eddie.dev/microsub
  pingback: https://webmention.io/eddie.dev/xmlrpc