Ash:
  representitive: url
  url: http://ashleyhinkle.com
  fb: https://www.facebook.com/ashleybhinkle
Mom:
  representitive: fb
  fb: https://www.facebook.com/sarah.hinkle.5
Dad: 
  representitive: fb
  fb: https://www.facebook.com/dean.hinkle
Eli:
  representitive: twitter
  fb: https://www.facebook.com/eli.choi
  twitter: https://twitter.com/elidchoi
Helen:
  representitive: fb
  fb: https://www.facebook.com/profile.php?id=530666733
Phil:
  representitive: fb
  fb: https://www.facebook.com/philly.joe.3
Jean:
  representitive: fb
  fb: https://www.facebook.com/jeansunmi
Sarah:
  representitive: fb
  fb: https://www.facebook.com/sarah.wilson.96155669
Cindy:
  representitive: fb
  fb: https://www.facebook.com/cindy.wilson.52206654
Eric:
  representitive: fb
  fb: https://www.facebook.com/eric.silva.96434
Ben:
  representitive: fb
  fb: https://www.facebook.com/profile.php?id=7028461