Ash:
  nickname: Ash
  firstName: Ashley
  lastName: Hinkle
  representitiveUrl: url
  url: https://ashleyhinkle.com
  facebook: https://www.facebook.com/ashleybhinkle
Luke:
  nickname: Luke
  firstName: Luke
  lastName: Hinkle
  representitiveUrl: url
  url: https://luke.hinkle.life
Mom:
  nickname: Mom
  firstName: Sarah
  lastName: Hinkle
  representitiveUrl: facebook
  facebook: https://www.facebook.com/sarah.hinkle.5
Dad:
  nickname: Dad
  firstName: Dean
  lastName: Hinkle
  representitiveUrl: facebook
  facebook: https://www.facebook.com/dean.hinkle
Jasmine:
  nickname: Jasmine
  firstName: Jasmine
  lastName: Hinkle
  representitiveUrl: url
  url: https://jasmine.hinkle.pet
Fiona:
  nickname: Fiona
  firstName: Fiona
  lastName: Hinkle
  representitiveUrl: url
  url: https://fiona.hinkle.pet
Eli:
  nickname: Eli
  firstName: Eli
  lastName: Choi
  representitiveUrl: twitter
  facebook: https://www.facebook.com/eli.choi
  twitter: https://twitter.com/elidchoi
Helen:
  nickname: Helen
  firstName: Helen
  lastName: Choi
  representitiveUrl: facebook
  facebook: https://www.facebook.com/profile.php?id=530666733
Phil:
  nickname: Phil
  firstName: Phil
  lastName: ?
  representitiveUrl: facebook
  facebook: https://www.facebook.com/philly.joe.3
Jean:
  nickname: Jean
  firstName: Jean
  lastName: ?
  representitiveUrl: facebook
  facebook: https://www.facebook.com/jeansunmi
Sarah:
  nickname: Sarah
  firstName: Sarah
  lastName: Wilson
  representitiveUrl: facebook
  facebook: https://www.facebook.com/sarah.wilson.96155669
Cindy:
  nickname: Cindy
  firstName: Cindy
  lastName: Wilson
  representitiveUrl: facebook
  facebook: https://www.facebook.com/cindy.wilson.52206654
Eric:
  nickname: Eric
  firstName: Eric
  lastName: Silva
  representitiveUrl: facebook
  facebook: https://www.facebook.com/eric.silva.96434
Ben:
  nickname: Ben
  firstName: Ben
  lastName: Hegler
  representitiveUrl: facebook
  facebook: https://www.facebook.com/profile.php?id=7028461
Marty:
  nickname: Marty
  firstName: Marty
  lastName: McGuire
  representitiveUrl: url
  url: https://martymcgui.re/
Jonathan:
  nickname: Jonathan
  firstName: Jonathan
  lastName: Prozzi
  representitiveUrl: url
  url: https://jonathanprozzi.net/
Manton:
  nickname: Manton
  firstName: Manton
  lastName: Reece
  representitiveUrl: microblog
  microblog: https://micro.blog/manton