 - name: "Micro.blog"
   uid: "https://micro.blog/EddieHinkle"
   shortcode: "mb"
 - name: "twitter/@eddiehinkle"
   uid: "https://twitter.com/eddiehinkle"
   shortcode: "t"
 - name: "Luke's Site"
   uid: "https://luke.hinkle.life"
   shortcode: "l"
 - name: "IndieNews"
   uid: "https://news.indieweb.org/en"
   shortcode: "in"
 - name: "xyz/en/cats"
   uid: "https://indieweb.xyz/en/cats"
   shortcode: "xyz/cats" 