 - name: "twitter.com/eddiehinkle"
   uid: "https://twitter.com/eddiehinkle"
   shortcode: "t"
 - name: "facebook.com/edwardthinkle"
   uid: "https://www.facebook.com/EdwardTHinkle"
   shortcode: "fb"
 - name: "twitter.com/edwardhinkle"
   uid: "https://twitter.com/edwardhinkle"
   shortcode: "tpro"
 - name: "twitter.com/AuthorsNoteFM"
   uid: "https://twitter.com/AuthorsNoteFM"
   shortcode: "tan"
 - name: "IndieNews"
   uid: "https://news.indieweb.org/en"
   shortcode: "in"
 - name: "Micro.blog"
   uid: "https://micro.blog/EddieHinkle"
   shortcode: "mb"
 - name: "github.com/EdwardHinkle"
   uid: "https://github.com/EdwardHinkle"
   shortcode: "gh"
 - name: "xyz/en/cats"
   uid: "https://indieweb.xyz/en/cats"
   shortcode: "xyz/cats" 